enum Colors {
	WHITE = '#FFFFFF',
	INACTIVE_GREY_FONT = '#989898',
	SUPER_LIGHT_ERROR_RED_BACKGROUND = '#FFF2F0',
	LIGHT_ERROR_RED_BORDER = '#ffccc7',
	BLUE_WISH = '#005CC9',
	BLACK = '#000000',
}

export default Colors
