name: Build
on:
 push:
  branches:
   - test-Artemiy.V-cicd-config
jobs:
 build:
  runs-on: self-hosted
  steps:
   - name: Create .env file
     uses: SpicyPizza/create-envfile@v2.0.3
     with:
      envkey_GENERATE_SOURCEMAP: ${{ secrets.GENERATE_SOURCEMAP }}
      envkey_VITE_API_URL: ${{ secrets.VITE_API_URL }}
      envkey_VITE_CLOUD_URL: ${{ secrets.VITE_CLOUD_URL }}
      envkey_VITE_IS_BETA: ${{ secrets.VITE_IS_BETA }}
      file_name: .env
      fail_on_empty: false
      sort_keys: false
   - name: Set up QEMU
     uses: docker/setup-qemu-action@v2
   - run: cat .env
   - run: ls -a
   - run: ls
   - name: Log in to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v2
   - run: ls
   - name: Build and push
     uses: docker/build-push-action@v3
     with:
      file: Dockerfile
      push: true
      tags: jsink/personal-account-frontend:latest
   - run: ls
 deploy:
  needs: build
  runs-on: self-hosted
  steps:
   - run: docker stop /wish-edu-pa-frontend
   - run: docker rm /wish-edu-pa-frontend
   - name: Pull image from docker hub
     run: docker pull jsink/personal-account-frontend:latest
   - name: Rename pulled docker image
     run: docker image tag jsink/personal-account-frontend:latest wish-edu-pa-frontend
   - name: Run docker container
     run: docker run --name wish-edu-pa-frontend -d -p 81:80 wish-edu-pa-frontend
